#!/bin/bash

if [[ "$(pwd)" == /mnt/* ]]
then
	if [[ "$*" == *rev-parse* ]]
	then
		output=$(git.exe "$@" | tr -d '\0')
		if [[ $output == [A-Z]:/* ]]
		then
			echo -n $(wslpath -u $output)
		else
			echo -n "$output"
		fi
	else
		git.exe "$@"
	fi
else
    /usr/bin/git "$@"
fi
